name: ASD_Backend feature pr cicd pipeline

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches: [ "main" ]

jobs:
  compile_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Validate pom.xml
        run: mvn validate
      - name: Clean the previous files
        run: mvn -e clean

      - name: Build
        run: mvn compiler:compile

      - name: run all tests
        run: mvn test